// Auto-generated by database/build_machine_exports.py from Staff Timetable (PORTAL).xlsx
// Re-run: python database/build_machine_exports.py
// termStaffWeekdayIndicesByProfileKey = weekdays (Sun=0..Sat=6) from timetable + staff_clients_machine roster.
window.PORTAL_TERM_FROM_TIMETABLE = {
  "termName": "Summer Term 2026",
  "termCalendarYear": 2026,
  "termCalendarMonths": [
    3,
    4,
    5,
    6
  ],
  "termCalendarFirstDom": {
    "3": 13
  },
  "termDashboardCalendarYear": 2026,
  "termDashboardCalendarMonths": [
    5,
    6
  ],
  "termDashboardCalendarFirstDom": {},
  "termDashboardCalendarFrom": "2026-06-01",
  "termDashboardCalendarTo": "2026-07-17",
  "firstDate": "2026-04-13",
  "lastDate": "2026-07-17",
  "termBreakFrom": "2026-05-23",
  "termBreakTo": "2026-05-31",
  "termResumeDate": "2026-06-01",
  "termClosedDates": [
    "2026-05-04"
  ],
  "termStaffAwayDatesByProfileKey": {
    "roberto": [
      "2026-05-07"
    ]
  },
  "termStaffOffWeekdaysRangeByProfileKey": {
    "roberto": {
      "from": "2026-06-01",
      "to": "2026-07-17",
      "weekdays": [
        6
      ]
    }
  },
  "termStaffFeedbackCompleteDatesByProfileKey": {
    "roberto": [
      "2026-05-17",
      "2026-05-22"
    ]
  },
  "termClientFirstSessionDate": {
    "amaar_ah": "2026-04-24"
  },
  "termHalfTermWeekStarts": [
    "2026-05-25"
  ],
  "termStaffWeekdayIndicesByProfileKey": {
    "alex": [
      0
    ],
    "angel": [
      1,
      2
    ],
    "aurora": [
      0,
      2,
      4
    ],
    "berta": [
      0,
      3
    ],
    "bismark": [
      0,
      1,
      3,
      5
    ],
    "carlos": [
      0,
      1,
      3,
      5
    ],
    "dan": [
      0,
      1,
      3,
      4
    ],
    "giuseppe": [
      0,
      1,
      3,
      5
    ],
    "godsway": [
      0,
      3
    ],
    "javi": [
      0,
      4
    ],
    "javier": [
      0,
      2,
      3,
      4
    ],
    "john": [
      0,
      1,
      3,
      5
    ],
    "lulia": [
      1,
      2,
      3,
      5
    ],
    "luliya": [
      1,
      2,
      3,
      5
    ],
    "michelle": [
      1,
      2,
      3,
      5
    ],
    "raul": [
      1,
      2,
      3,
      4,
      5
    ],
    "roberto": [
      0,
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "sandra": [
      1
    ],
    "simon": [
      4
    ],
    "victor": [
      1,
      2,
      3,
      4,
      5
    ],
    "youssef": [
      0,
      1,
      2,
      3,
      5,
      6
    ]
  },
  "termStaffWeekdayIndicesDashboardByProfileKey": {
    "alex": [
      0
    ],
    "angel": [
      1,
      2
    ],
    "aurora": [
      0,
      2,
      4
    ],
    "berta": [
      0,
      3
    ],
    "bismark": [
      0,
      1,
      3,
      5
    ],
    "carlos": [
      0,
      1,
      3,
      5
    ],
    "dan": [
      0,
      1,
      3,
      4
    ],
    "giuseppe": [
      0,
      1,
      3,
      5
    ],
    "godsway": [
      0,
      3
    ],
    "javi": [
      0
    ],
    "javier": [
      0,
      2,
      3,
      4
    ],
    "john": [
      0,
      1,
      3,
      5
    ],
    "lulia": [
      1,
      2,
      3,
      5
    ],
    "luliya": [
      1,
      2,
      3,
      5
    ],
    "michelle": [
      1,
      2,
      3,
      5
    ],
    "raul": [
      1,
      3,
      4,
      5
    ],
    "roberto": [
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "sandra": [
      1
    ],
    "simon": [
      4
    ],
    "victor": [
      1,
      2,
      3,
      4,
      5
    ],
    "youssef": [
      0,
      1,
      2,
      3,
      5,
      6
    ]
  }
};
