/**
 * Participant gender map for the staff/lead "Participants" directory.
 *
 * The roster + profile sheets do NOT carry a structured gender field, so the
 * dashboard colours each participant button blue (male) / pink (female) from
 * this map. Keys are matched (in order) by client slug, full name (lowercase),
 * or FIRST NAME (lowercase) — so "Abodi P" and "Abodi Pa" both resolve via
 * "abodi". Anything not listed here uses the soft blue neutral tile style.
 *
 * EDIT FREELY: add or correct entries as "name": "m" | "f".
 */
window.PORTAL_CLIENT_GENDER_OVERRIDES = {
  // Female
  amber: "f",
  aqsa: "f",
  cayra: "f",
  emani: "f",
  gemma: "f",
  ikram: "f",
  kareena: "f",
  karo: "f",
  kate: "f",
  kirushy: "f",
  linda: "f",
  maiyar: "f",
  mia: "f",
  nina: "f",
  serine: "f",
  stephanie: "f",
  vithura: "f",
  zayana: "f",

  // Male
  abodi: "m",
  bediako: "m",
  adaam: "m",
  aadam: "m",
  adam: "m",
  amaar: "m",
  amar: "m",
  amir: "m",
  arthur: "m",
  ayaan: "m",
  aydaan: "m",
  ayman: "m",
  cyrus: "m",
  eddie: "m",
  eiji: "m",
  elijah: "m",
  emanuel: "m",
  erik: "m",
  fadi: "m",
  faris: "m",
  gabriel: "m",
  haider: "m",
  haneef: "m",
  hazem: "m",
  jack: "m",
  jad: "m",
  jibril: "m",
  joel: "m",
  junaid: "m",
  kayden: "m",
  khaled: "m",
  khalid: "m",
  logan: "m",
  lucca: "m",
  mario: "m",
  matthias: "m",
  max: "m",
  mohammed: "m",
  ned: "m",
  rayan: "m",
  rayyan: "m",
  richard: "m",
  ruben: "m",
  saaib: "m",
  sambhav: "m",
  sammer: "m",
  scott: "m",
  shaan: "m",
  simon: "m",
  steven: "m",
  thushyan: "m",
  timi: "m",
  tinashe: "m",
  tom: "m",
  tyson: "m",
  yaqoub: "m",
  yassir: "m",
  yoan: "m",
  yossi: "m",
  yousef: "m",
  yunis: "m",
  yusuf: "m",
  zaid: "m",
  zakariya: "m",
};
