// Auto-generated by database/build_machine_exports.py from Staff Timetable (PORTAL).xlsx
// Re-run: python database/build_machine_exports.py
// termStaffWeekdayIndicesByProfileKey = weekdays (Sun=0..Sat=6) from timetable + staff_clients_machine roster.
window.PORTAL_TERM_FROM_TIMETABLE = {
  "termName": "Summer Term 2026",
  "termCalendarYear": 2026,
  "termCalendarMonths": [
    3,
    4,
    5,
    6
  ],
  "termCalendarFirstDom": {
    "3": 13
  },
  "firstDate": "2026-04-13",
  "lastDate": "2026-07-17",
  "termHalfTermWeekStarts": [
    "2026-05-25"
  ],
  "termStaffWeekdayIndicesByProfileKey": {
    "angel": [
      1,
      2
    ],
    "aurora": [
      0,
      2,
      4
    ],
    "berta": [
      0,
      3
    ],
    "bismark": [
      0,
      1,
      3,
      5
    ],
    "carlos": [
      0
    ],
    "dan": [
      0,
      1,
      3,
      4
    ],
    "giuseppe": [
      0,
      1,
      3,
      5
    ],
    "javier": [
      0,
      2,
      3,
      4
    ],
    "john": [
      0,
      1,
      5
    ],
    "new": [
      4
    ],
    "raul": [
      3,
      5
    ],
    "roberto": [
      0,
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "sandra": [
      1
    ],
    "victor": [
      1,
      2,
      3,
      4,
      5
    ],
    "youssef": [
      0,
      1,
      2,
      3,
      6
    ]
  }
};
