-- One-shot via CLI (repo root):
--   node database/local-vault/apply-madre-live-document.mjs
--
-- Manual: apply supabase/migrations/20260622150000_portal_madre_document.sql
-- Replace __PORTAL_MADRE_WEBHOOK_SECRET__ with PORTAL_PUSH_WEBHOOK_SECRET value.
