/**
 * Genera ELEMENTOR/MEDIOS/admin_dashboard.elementor-frame.js (Blob del documento admin).
 * El snippet iframe está en ELEMENTOR/MEDIOS/admin_dashboard.elementor.html (build_admin_embed_static_html.mjs).
 */
import fs from "fs";
import path from "path";
import { PORTAL_ADMIN_MEDIOS_V } from "./portal_admin_medios.mjs";
import { ELEMENTOR_MEDIOS_DIR, WORKING_UI_DIR } from "./elementor_medios_paths.mjs";

const root = WORKING_UI_DIR;
const fragmentPath = path.join(root, "admin_dashboard.html");
const jsOut = path.join(ELEMENTOR_MEDIOS_DIR, "admin_dashboard.elementor-frame.js");

const CHUNK = 6000;

const fragment = fs.readFileSync(fragmentPath, "utf8").trim();

const fullDoc = `<!DOCTYPE html>
<html lang="en-GB" data-portal-session-feedback-v="${PORTAL_ADMIN_MEDIOS_V}" data-portal-clients-payments-v="${PORTAL_ADMIN_MEDIOS_V}" data-portal-waiting-list-v="${PORTAL_ADMIN_MEDIOS_V}">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
<title>clubSENsational · Admin</title>
</head>
<body>
${fragment}
</body>
</html>
`;

const b64 = Buffer.from(fullDoc, "utf8").toString("base64");
const chunks = [];
for (let i = 0; i < b64.length; i += CHUNK) {
  chunks.push(b64.slice(i, i + CHUNK));
}

const jsBody = [
  "/* clubSENsational — admin Elementor iframe boot (generated by build_admin_dashboard_elementor_frame.mjs) */",
  "(function () {",
  "  function b64ToUtf8(b64) {",
  "    var bin = atob(b64);",
  "    var bytes = new Uint8Array(bin.length);",
  "    for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);",
  '    return new TextDecoder("utf-8").decode(bytes);',
  "  }",
  "  function boot() {",
  '    var frame = document.getElementById("portalAdminFrame");',
  "    if (!frame) {",
  '      if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);',
  "      return;",
  "    }",
  "    try {",
  "      var parts = [",
  chunks.map((c) => JSON.stringify(c)).join(",\n"),
  "      ];",
  '      var html = b64ToUtf8(parts.join(""));',
  '      var blob = new Blob([html], { type: "text/html;charset=utf-8" });',
  "      frame.src = URL.createObjectURL(blob);",
  "    } catch (e) {",
  '      try { console.error("portalAdminFrame boot", e); } catch (_) {}',
  "    }",
  "  }",
  "  boot();",
  "})();",
  "",
].join("\n");

fs.mkdirSync(path.dirname(jsOut), { recursive: true });
fs.writeFileSync(jsOut, jsBody, "utf8");

console.log("Wrote", jsOut, { jsBytes: Buffer.byteLength(jsBody, "utf8"), b64Len: b64.length, chunks: chunks.length });
