/**
 * Genera ELEMENTOR/MEDIOS/admin_dashboard.styles.loader.js (CSS minificado en base64).
 * Actualiza ?v= del script en admin_dashboard.html (no toca el resto del HTML).
 */
import fs from "fs";
import path from "path";
import { PORTAL_ADMIN_MEDIOS_BASE, PORTAL_ADMIN_MEDIOS_V } from "./portal_admin_medios.mjs";
import { ELEMENTOR_MEDIOS_DIR, WORKING_UI_DIR } from "./elementor_medios_paths.mjs";
import { syncElementorMediosDatabaseAssets } from "./sync_elementor_medios_database_assets.mjs";

const root = WORKING_UI_DIR;

await syncElementorMediosDatabaseAssets();
const cssPath = path.join(root, "css", "admin_dashboard.css");
const jsOut = path.join(ELEMENTOR_MEDIOS_DIR, "admin_dashboard.styles.loader.js");
const htmlPath = path.join(root, "admin_dashboard.html");

function minifyCssForAdminInline(source) {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\s+/g, " ")
    .replace(/\s*([{}:;,>+~])\s*/g, "$1")
    .replace(/;}/g, "}")
    .trim();
}

const cssUtf8 = minifyCssForAdminInline(fs.readFileSync(cssPath, "utf8"));
const b64 = Buffer.from(cssUtf8, "utf8").toString("base64");
const CHUNK = 6000;
const chunks = [];
for (let i = 0; i < b64.length; i += CHUNK) {
  chunks.push(b64.slice(i, i + CHUNK));
}

const body = [
  "/* clubSENsational — admin CSS injector (generated by build_admin_dashboard_styles_loader.mjs) */",
  "(function () {",
  "  try {",
  "    var parts = [",
  chunks.map((c) => JSON.stringify(c)).join(",\n"),
  "    ];",
  '    var b64 = parts.join("");',
  "    var bin = atob(b64);",
  "    var bytes = new Uint8Array(bin.length);",
  "    for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);",
  '    var css = new TextDecoder("utf-8").decode(bytes);',
  '    var el = document.createElement("style");',
  '    el.setAttribute("data-portal-admin-css", "1");',
  "    el.textContent = css;",
  "    (document.head || document.documentElement).appendChild(el);",
  "  } catch (e) {}",
  "})();",
  "",
].join("\n");

fs.mkdirSync(path.dirname(jsOut), { recursive: true });
fs.writeFileSync(jsOut, body, "utf8");

let html = fs.readFileSync(htmlPath, "utf8");
const loaderRe = new RegExp(
  `(${PORTAL_ADMIN_MEDIOS_BASE.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}/admin_dashboard\\.styles\\.loader\\.js\\?)v=[^"]+`,
  "g"
);
const hadLoader = html.includes("admin_dashboard.styles.loader.js");
if (hadLoader) {
  loaderRe.lastIndex = 0;
  html = html.replace(loaderRe, `$1v=${PORTAL_ADMIN_MEDIOS_V}`);
  fs.writeFileSync(htmlPath, html, "utf8");
} else {
  console.warn("No admin_dashboard.styles.loader.js src found in admin_dashboard.html — only wrote JS file.");
}

console.log("Wrote", jsOut, { jsBytes: Buffer.byteLength(body, "utf8"), b64Len: b64.length, chunks: chunks.length });
if (hadLoader) console.log("Updated styles loader ?v= in admin_dashboard.html", { v: PORTAL_ADMIN_MEDIOS_V });
