-- Seed the LA + 'No re-enroled' cohorts into public.client_payments.
-- Generated from 'SUMMER. Re-enrolments, june 2026.xlsx' (sheets LA / No re-enroled).
-- The original local seed only loaded PARENTS, so LA-funded participants
-- (Ealing / H&F / NHS) had no funding record. Idempotent: re-running replaces
-- ONLY these two sheets (PARENTS rows + any admin edits there are untouched).

begin;

delete from public.client_payments where sheet in ('LA', 'No re-enroled');

insert into public.client_payments
  (sheet, row_index, client_key, client_name, parent_name, payment_status, amount, data, source_file)
values
  ('LA', 1000, 'adaam-ah', 'Adaam Ah', 'Ealing (Leila)', 'Outstanding', null, '{"Services": "30'' SW (Mon), 90’ S&C (Su)", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "auto-monthly (30'' AA Summer - 90'' MA Summer)", "Invoice": "n/a", "Parent / LA": "Ealing (Leila)", "Cost": "50 + 120", "Sessions": "13 & 11", "VAT": "Exempt", "Payment status": "Outstanding"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1001, 'amaar-ah', 'Amaar Ah', 'Ealing (Leila)', 'Outstanding', null, '{"Services": "30'' SW (Mon).30'' SW (Mon), 90’ S&C (Su)", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "auto-monthly (30'' AA Spring - 30'' AA Summer - 90'' MA Summer)", "Invoice": "n/a", "Parent / LA": "Ealing (Leila)", "Cost": "—", "Sessions": "—", "VAT": "Exempt", "Payment status": "Outstanding"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1002, 'amar-rai', 'Amar Rai', 'Ealing (Kiren)', 'Paid', null, '{"Services": "60’ SW (Mo & Wed)", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "auto-monthly (2 x 60'' AA)", "Invoice": "n/a", "Parent / LA": "Ealing (Kiren)", "Cost": "200", "Sessions": "13", "VAT": "Exempt", "Payment status": "Paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1003, 'aydaan-ah', 'Aydaan Ah', 'Ealing (Leila)', 'Outstanding', null, '{"Services": "30'' SW (Tu), 90’ S&C (Su)", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "auto-monthly (30'' AA Summer - 90'' MA Summer)", "Invoice": "n/a", "Parent / LA": "Ealing (Leila)", "Cost": "50 + 120", "Sessions": "13 & 11", "VAT": "Exempt", "Payment status": "Outstanding"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1004, 'samer', 'Samer', 'Ealing (Bhakiet)', 'Paid', null, '{"Services": "90’ S&C (Su)", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "auto-monthly (2x 90'' MA Spring - 90'' MA Summer)", "Invoice": "n/a", "Parent / LA": "Ealing (Bhakiet)", "Cost": "120", "Sessions": "11", "VAT": "Exempt", "Payment status": "Paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1005, 'steven', 'Steven', 'Ealing (Amashaman)', 'Paid', null, '{"Services": "30’ SW (Mo)", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "auto-monthly (30'' AA Summer)", "Invoice": "n/a", "Parent / LA": "Ealing (Amashaman)", "Cost": "50", "Sessions": "13", "VAT": "Exempt", "Payment status": "Paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1006, 'tinashe', 'Tinashe', 'Pat / Ealing', 'Paid', null, '{"Services": "90’ Bespoke (Mo & We)", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "auto-monthly (2x 90'' BP Summer)", "Invoice": "n/a", "Parent / LA": "Pat / Ealing", "Cost": "714.84", "Sessions": "13", "VAT": "Exempt", "Payment status": "Paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1007, 'abodi-patel', 'Abodi Patel', 'Maya / Ealing', 'Paid', null, '{"Services": "60’ SW (Mo)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "Paid", "Invoice": "n/a", "Parent / LA": "Maya / Ealing", "Cost": "0", "Sessions": "0", "VAT": "Exempt", "Payment status": "Paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1008, 'adam-p', 'Adam P', '/ Asabre', 'Paid', null, '{"Services": "April - 90’ SW (Mo)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "April (2x Monday 90'' AA & 1x Friday 90'' AA", "Invoice": "263", "Parent / LA": "/ Asabre", "Cost": "150", "Sessions": "3", "VAT": "Exempt", "Payment status": "Paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1009, 'adam-p', 'Adam P', '/ Asabre', 'Not paid', null, '{"Services": "July - 90’ SW (Mo)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "July (2x Monday 90'' AA & 3x Friday 90'' AA", "Invoice": "266", "Parent / LA": "/ Asabre", "Cost": "150", "Sessions": "2", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1010, 'adam-p', 'Adam P', '/ Asabre', 'Not paid', null, '{"Services": "June - 90’ SW (Mo)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "June (5x Monday 90'' AA & 4x Friday 90'' AA", "Invoice": "265", "Parent / LA": "/ Asabre", "Cost": "150", "Sessions": "5", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1011, 'adam-p', 'Adam P', '/ Asabre', 'Not paid', null, '{"Services": "May - 90’ SW (Mo)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "May (3x Monday 90'' AA & 4x Friday 90'' AA", "Invoice": "264", "Parent / LA": "/ Asabre", "Cost": "150", "Sessions": "3", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1012, 'elijah', 'Elijah', 'Amy / Anouk', 'Paid', null, '{"Services": "30’ SW (Th)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "Paid", "Invoice": "n/a", "Parent / LA": "Amy / Anouk", "Cost": "0", "Sessions": "0", "VAT": "Exempt", "Payment status": "Paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1013, 'matthias', 'Matthias', 'Kiya / Jan', 'Not paid', null, '{"Services": "60’ SW (Sat)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "60'' AA Summer", "Invoice": "inv 0267", "Parent / LA": "Kiya / Jan", "Cost": "100", "Sessions": "11", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1014, 'saiib', 'Saiib', 'Ahmed / Anouk', 'Not paid', null, '{"Services": "30’ SW (Sa)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "30'' AA Summer", "Invoice": "inv 0268", "Parent / LA": "Ahmed / Anouk", "Cost": "50", "Sessions": "11", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1015, 'simon', 'Simon', 'Sara / Anouk', 'Not paid', null, '{"Services": "30’ SW (Su)x2 + 30’ SW(Su)x11", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "30'' SW Summer", "Invoice": "inv 0269", "Parent / LA": "Sara / Anouk", "Cost": "50", "Sessions": "13", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1016, 'yassir', 'Yassir', 'Nadia / Rihanna', 'Not paid', null, '{"Services": "60'' SW (Tu)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "April", "Invoice": "336", "Parent / LA": "Nadia / Rihanna", "Cost": "100", "Sessions": "3", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1017, 'yassir', 'Yassir', 'Nadia / Rihanna', 'Not paid', null, '{"Services": "60'' SW (Tu)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "July", "Invoice": "—", "Parent / LA": "Nadia / Rihanna", "Cost": "100", "Sessions": "2", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1018, 'yassir', 'Yassir', 'Nadia / Rihanna', 'Not paid', null, '{"Services": "60'' SW (Tu)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "June", "Invoice": "—", "Parent / LA": "Nadia / Rihanna", "Cost": "100", "Sessions": "5", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1019, 'yassir', 'Yassir', 'Nadia / Rihanna', 'Not paid', null, '{"Services": "60'' SW (Tu)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "May", "Invoice": "Inv 352", "Parent / LA": "Nadia / Rihanna", "Cost": "100", "Sessions": "3", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1020, 'tinashe', 'Tinashe', 'Pat / ILa', 'Paid', null, '{"Services": "90’ Bespoke (F) - April", "Funding": "Local authority · NHS / ILA", "Funder": "NHS / ILA", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "April x2 Friday 90'' BP", "Invoice": "—", "Parent / LA": "Pat / ILa", "Cost": "357.42", "Sessions": "2", "VAT": "Exempt", "Payment status": "Paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1021, 'tinashe', 'Tinashe', 'Pat / ILa', 'Not paid', null, '{"Services": "90’ Bespoke (F) - July", "Funding": "Local authority · NHS / ILA", "Funder": "NHS / ILA", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "July x3 Friday 90'' BP", "Invoice": "—", "Parent / LA": "Pat / ILa", "Cost": "357.42", "Sessions": "3", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1022, 'tinashe', 'Tinashe', 'Pat / ILa', 'Not paid', null, '{"Services": "90’ Bespoke (F) - June", "Funding": "Local authority · NHS / ILA", "Funder": "NHS / ILA", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "June x4 Friday 90'' BP", "Invoice": "—", "Parent / LA": "Pat / ILa", "Cost": "357.42", "Sessions": "4", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1023, 'tinashe', 'Tinashe', 'Pat / ILa', 'Not paid', null, '{"Services": "90’ Bespoke (F) - May", "Funding": "Local authority · NHS / ILA", "Funder": "NHS / ILA", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "May x4 Friday 90'' BP", "Invoice": "Inv 351", "Parent / LA": "Pat / ILa", "Cost": "357.42", "Sessions": "4", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1024, 'fadi', 'Fadi', 'Nora / NHS', 'Paid', null, '{"Services": "April - Convo (Mo-Fri) x 15", "Funding": "Local authority · NHS / SBS", "Funder": "NHS / SBS", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "April x15 sessions", "Invoice": "335", "Parent / LA": "Nora / NHS", "Cost": "647.5", "Sessions": "15", "VAT": "Exempt", "Payment status": "Paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1025, 'fadi', 'Fadi', 'Nora / NHS', 'Not paid', null, '{"Services": "July - Convo (Mo-Fri) x 13", "Funding": "Local authority · NHS / SBS", "Funder": "NHS / SBS", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "July x13 sessions", "Invoice": "—", "Parent / LA": "Nora / NHS", "Cost": "647.5", "Sessions": "13", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1026, 'fadi', 'Fadi', 'Nora / NHS', 'Not paid', null, '{"Services": "June - Convo (Mo-Fri) x 22", "Funding": "Local authority · NHS / SBS", "Funder": "NHS / SBS", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "June x22 sessions", "Invoice": "—", "Parent / LA": "Nora / NHS", "Cost": "647.5", "Sessions": "22", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1027, 'fadi', 'Fadi', 'Nora / NHS', 'Not paid', null, '{"Services": "May - Convo (Mo-Fri) x 15", "Funding": "Local authority · NHS / SBS", "Funder": "NHS / SBS", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "May x15 sessions", "Invoice": "339", "Parent / LA": "Nora / NHS", "Cost": "647.5", "Sessions": "15", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('LA', 1028, 'faris', 'Faris', 'Hiyam / H&F', 'Not paid', 550.0, '{"Services": "30’ SW (Su)", "Funding": "Local authority · H&F (Hammersmith & Fulham)", "Funder": "H&F (Hammersmith & Fulham)", "Payment method": "LA invoice", "Term": "Summer term 2026", "Month": "30'' AA Summer", "Invoice": "inv 332", "Parent / LA": "Hiyam / H&F", "Cost": "50", "Sessions": "11", "VAT": "Exempt", "Payment status": "Not paid"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('No re-enroled', 2000, 'mohamoud', 'Mohamoud', 'Nafiso', 'Not re-enrolled', null, '{"Services": "30'' SW (Sat)", "Funding": "Private (parents)", "Payment method": "Bank Transfer - 2", "Term": "Summer term 2026", "Note": "—", "Parent / LA": "Nafiso", "Cost": "50", "Sessions": "11", "VAT": "PF / VAT 20%"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('No re-enroled', 2001, 'summer', 'Summer', 'S. Messing', 'Not re-enrolled', null, '{"Services": "30’ SW (Sa)", "Funding": "Private (parents)", "Payment method": "Go Cardless", "Term": "Summer term 2026", "Note": "—", "Parent / LA": "S. Messing", "Cost": "50", "Sessions": "11", "VAT": "PF / VAT 20%"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('No re-enroled', 2002, 'jake', 'Jake', 'Kate', 'Not re-enrolled', null, '{"Services": "60’ CL(Th)", "Funding": "Private (parents)", "Payment method": "One - off payment", "Term": "Summer term 2026", "Note": "£70 Credit", "Parent / LA": "Kate", "Cost": "70", "Sessions": "1", "VAT": "PF / VAT 20%"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx'),
  ('No re-enroled', 2003, 'ismael', 'Ismael', '—', 'Not re-enrolled', null, '{"Services": "—", "Funding": "Private (parents)", "Payment method": "—", "Term": "Summer term 2026", "Note": "—", "Parent / LA": "—", "Cost": "—", "Sessions": "—", "VAT": "—"}'::json, 'SUMMER. Re-enrolments, june 2026.xlsx');

commit;
