-- Seed the LA / NHS cohort into public.client_payments.
-- Generated from 'LA_NHS 25_26 Payments (june 2026).xlsx' (the authoritative LBHF / NHS-ILA / NHS-SBS / Ealing ledger).
-- amount / Total = SUMMER TERM 2026 (principal); data.Next = YEAR-TO-DATE 25/26 (billed/paid/due).
-- Summer term length: 13 weekday (Mon-Fri) / 11 weekend (Sat-Sun) sessions (CEO-confirmed).
-- Summer is straight from the ledger where invoiced; Ealing CWD / Care-in-Finance summer is a
-- projection at the confirmed rate (weekday x13, weekend x11), flagged in 'Summer basis'.
-- Idempotent: re-running replaces ONLY the 'LA' sheet (PARENTS / No re-enroled untouched).

begin;

delete from public.client_payments where sheet = 'LA';

insert into public.client_payments
  (sheet, row_index, client_key, client_name, parent_name, payment_status, amount, data, source_file)
values
  ('LA', 1000, 'adam-p', 'Adam P', 'H&F · LD Team (Asabre)', 'Outstanding', 3150.00, '{"Services": "90'' Aquatic (Mon) + 90'' Aquatic (Fri)", "Funding": "Local authority · H&F", "Funder": "H&F (Hammersmith & Fulham)", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "LA invoice (BACS)", "Term": "Summer term 2026", "Cost": "£150 / session", "Sessions": "May–Jul · ~21 sess", "Invoice": "264 · 265 · 266", "VAT": "Exempt", "Next": "Yr 25/26: £7,200 billed · £3,450 paid · £3,750 due", "Summer basis": "May £1,050 + Jun £1,350 + Jul £750", "Year billed (25/26)": "£7,200", "Year received (25/26)": "£3,450", "Year outstanding": "£3,750", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1001, 'yassir', 'Yassir', 'H&F · LD Team (Castle-Weekes)', 'Outstanding', 500.00, '{"Services": "60'' Aquatic (Tue) / 30'' Aquatic (Thu)", "Funding": "Local authority · H&F", "Funder": "H&F (Hammersmith & Fulham)", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "LA invoice (BACS)", "Term": "Summer term 2026", "Cost": "£50–100 / session", "Sessions": "May–Jul · ~10 sess", "Invoice": "336 · 352", "VAT": "Exempt", "Next": "Yr 25/26: £9,250 billed · £8,450 paid · £800 due", "Summer basis": "May £150 + Jun £200 + Jul £150", "Year billed (25/26)": "£9,250", "Year received (25/26)": "£8,450", "Year outstanding": "£800", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1002, 'matthias', 'Matthias', 'H&F · Mulligan', 'Outstanding', 1100.00, '{"Services": "60'' Aquatic (Sat) 1:1", "Funding": "Local authority · H&F", "Funder": "H&F (Hammersmith & Fulham)", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "LA invoice (BACS)", "Term": "Summer term 2026", "Cost": "£100 / session", "Sessions": "11 (Summer term · Sat)", "Invoice": "267", "VAT": "Exempt", "Next": "Yr 25/26: £2,600 billed · £1,500 paid · £1,100 due", "Summer basis": "Summer term 11 × £100 (Sat)", "Year billed (25/26)": "£2,600", "Year received (25/26)": "£1,500", "Year outstanding": "£1,100", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1003, 'saiib', 'Saiib', 'H&F · Sabrosa', 'Outstanding', 550.00, '{"Services": "30'' Aquatic (Sat) 1:1", "Funding": "Local authority · H&F", "Funder": "H&F (Hammersmith & Fulham)", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "LA invoice (BACS)", "Term": "Summer term 2026", "Cost": "£50 / session", "Sessions": "11 (Summer term · Sat)", "Invoice": "268", "VAT": "Exempt", "Next": "Yr 25/26: £1,200 billed · £450 paid · £750 due", "Summer basis": "Summer term 11 × £50 (Sat)", "Year billed (25/26)": "£1,200", "Year received (25/26)": "£450", "Year outstanding": "£750", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1004, 'simon', 'Simon', 'H&F · Sabrosa', 'Outstanding', 650.00, '{"Services": "30'' Aquatic (Sat) 1:1", "Funding": "Local authority · H&F", "Funder": "H&F (Hammersmith & Fulham)", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "LA invoice (BACS)", "Term": "Summer term 2026", "Cost": "£50 / session", "Sessions": "13 (2 spring + Summer term)", "Invoice": "269", "VAT": "Exempt", "Next": "Yr 25/26: £650 billed · £0 paid · £650 due", "Summer basis": "13 × £50 (incl 2 spring weeks)", "Year billed (25/26)": "£650", "Year received (25/26)": "£0", "Year outstanding": "£650", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1005, 'elijah', 'Elijah', 'H&F · Mulligan', 'Paid', null, '{"Services": "30'' Aquatic (Thu) 1:1", "Funding": "Local authority · H&F", "Funder": "H&F (Hammersmith & Fulham)", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "LA invoice (BACS)", "Term": "Summer term 2026", "Cost": "—", "Sessions": "Whole Year 25/26", "Invoice": "0075", "VAT": "Exempt", "Next": "Yr 25/26: £1,850 billed · £1,850 paid (annual, settled)", "Summer basis": "billed Whole Year 25/26 (settled)", "Year billed (25/26)": "£1,850", "Year received (25/26)": "£1,850", "Year outstanding": "£0", "Payment status": "Paid"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1006, 'abodi-patel', 'Abodi Patel', 'H&F · Maya', 'Paid', null, '{"Services": "60'' Aquatic (Mon) 1:1", "Funding": "Local authority · H&F", "Funder": "H&F (Hammersmith & Fulham)", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "LA invoice (BACS)", "Term": "Summer term 2026", "Cost": "—", "Sessions": "Whole Year 25/26", "Invoice": "1704", "VAT": "Exempt", "Next": "Yr 25/26: £3,700 billed · £3,700 paid (annual, settled)", "Summer basis": "billed Whole Year 25/26 (settled)", "Year billed (25/26)": "£3,700", "Year received (25/26)": "£3,700", "Year outstanding": "£0", "Payment status": "Paid"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1007, 'faris', 'Faris', 'H&F · Sabrosa', 'Outstanding', 550.00, '{"Services": "30'' Aquatic (Sun) 1:1", "Funding": "Local authority · H&F", "Funder": "H&F (Hammersmith & Fulham)", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "LA invoice (BACS)", "Term": "Summer term 2026", "Cost": "£50 / session", "Sessions": "11 (projected · Sun)", "Invoice": "—", "VAT": "Exempt", "Next": "Spring 25/26: £470 paid · Summer not yet invoiced (≈£550)", "Summer basis": "projected 11 × £50 (Sun; summer not yet invoiced; Spring £470 paid)", "Year billed (25/26)": "£470", "Year received (25/26)": "£470", "Year outstanding": "£0", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1008, 'tinashe-nhs', 'Tinashe', 'NHS/ILA · Pat', 'Outstanding', 3931.62, '{"Services": "90'' Bespoke (Fri) 3:1", "Funding": "NHS · ILA (People Places)", "Funder": "NHS · ILA", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "NHS invoice (PO)", "Term": "Summer term 2026", "Cost": "£357.42 / session", "Sessions": "10 (May–Jul · Fri)", "Invoice": "(May–Jul)", "VAT": "Exempt", "Next": "Yr 25/26: £14,296.80 billed · £10,365.18 paid · £3,931.62 due", "Summer basis": "May £1,429.68 + Jun £1,429.68 + Jul £1,072.26", "Year billed (25/26)": "£14,296.80", "Year received (25/26)": "£10,365.18", "Year outstanding": "£3,931.62", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1009, 'fadi', 'Fadi', 'NHS/SBS · Prasher', 'Outstanding', 32375.00, '{"Services": "2:1 Bespoke 2h30 (Mon–Fri)", "Funding": "NHS · SBS", "Funder": "NHS · SBS", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "NHS invoice (PO)", "Term": "Summer term 2026", "Cost": "£647.50 / session", "Sessions": "May–Jul · ~50 sess", "Invoice": "338", "VAT": "Exempt", "Next": "Yr 25/26: £119,787.50 billed · £87,412.50 paid · £32,375 due", "Summer basis": "May £9,712.50 + Jun £14,245 + Jul £8,417.50", "Year billed (25/26)": "£119,787.50", "Year received (25/26)": "£87,412.50", "Year outstanding": "£32,375", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1010, 'ikram-omar', 'Ikram Omar', 'NHS/SBS · Day Centre', 'Outstanding', 33000.00, '{"Services": "2:1 Day Centre 5h (Mon–Wed & Fri)", "Funding": "NHS · SBS", "Funder": "NHS · SBS", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "NHS invoice (PO)", "Term": "Summer term 2026", "Cost": "£750 / session", "Sessions": "May–Jul · ~44 sess", "Invoice": "—", "VAT": "Exempt", "Next": "Yr 25/26: £44,460 billed · £0 paid · £44,460 due", "Summer basis": "May £9,750 + Jun £13,500 + Jul £9,750", "Year billed (25/26)": "£44,460", "Year received (25/26)": "£0", "Year outstanding": "£44,460", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1011, 'emmanuel', 'Emmanuel', 'NHS/SBS · Day Centre', 'Outstanding', 8000.00, '{"Services": "1:1 Day Centre 5h (Mon, Wed & Fri)", "Funding": "NHS · SBS", "Funder": "NHS · SBS", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "NHS invoice (PO)", "Term": "Summer term 2026", "Cost": "£500 / session", "Sessions": "Jun–Jul · ~16 sess", "Invoice": "—", "VAT": "Exempt", "Next": "Yr 25/26: £8,000 billed · £0 paid · £8,000 due", "Summer basis": "Jun £4,000 + Jul £4,000", "Year billed (25/26)": "£8,000", "Year received (25/26)": "£0", "Year outstanding": "£8,000", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1012, 'tinashe', 'Tinashe', 'Ealing · Pat', 'Outstanding', 8970.00, '{"Services": "2× 90'' Bespoke (Mon & Wed) 3:1", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "Direct payment (CWD remittance)", "Term": "Summer term 2026", "Cost": "£690 / week", "Sessions": "13 wks (projected · weekday)", "Invoice": "—", "VAT": "Exempt", "Next": "Yr 25/26 (Ealing): £16,595.04 billed · £16,595.04 paid · Summer not yet invoiced (≈£8,970)", "Summer basis": "projected £690/wk × 13 (weekday; summer not yet invoiced)", "Year billed (25/26)": "£16,595.04", "Year received (25/26)": "£16,595.04", "Year outstanding": "£0", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1013, 'steven', 'Steven', 'Ealing · Cesare', 'Outstanding', 650.00, '{"Services": "30'' Aquatic (Mon) 1:1", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "Direct payment (CWD remittance)", "Term": "Summer term 2026", "Cost": "£50 / week", "Sessions": "13 wks (projected · weekday)", "Invoice": "—", "VAT": "Exempt", "Next": "Yr 25/26: £1,187.96 billed · £1,187.96 paid · Summer not yet invoiced (≈£650)", "Summer basis": "projected £50/wk × 13 (weekday; summer not yet invoiced)", "Year billed (25/26)": "£1,187.96", "Year received (25/26)": "£1,187.96", "Year outstanding": "£0", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1014, 'amar-rai', 'Amar-Rai', 'Ealing · Kiren (mother)', 'Outstanding', 2600.00, '{"Services": "2× 60'' Aquatic (Mon & Wed) 1:1", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "Direct payment (CWD remittance)", "Term": "Summer term 2026", "Cost": "£200 / week", "Sessions": "13 wks (projected · weekday)", "Invoice": "—", "VAT": "Exempt", "Next": "Yr 25/26: £4,751.80 billed · £4,751.80 paid · Summer not yet invoiced (≈£2,600)", "Summer basis": "projected £200/wk × 13 (weekday; summer not yet invoiced)", "Year billed (25/26)": "£4,751.80", "Year received (25/26)": "£4,751.80", "Year outstanding": "£0", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1015, 'samer', 'Samer', 'Ealing · Bakhiet', 'Outstanding', 1320.00, '{"Services": "90'' Multi-Activity (Sun) 1:1", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "Direct payment (CWD remittance)", "Term": "Summer term 2026", "Cost": "£120 / week", "Sessions": "11 wks (projected · weekend)", "Invoice": "—", "VAT": "Exempt", "Next": "Yr 25/26: £1,486.82 billed · £1,486.82 paid · Summer not yet invoiced (≈£1,320)", "Summer basis": "projected £120/wk × 11 (Sun; summer not yet invoiced)", "Year billed (25/26)": "£1,486.82", "Year received (25/26)": "£1,486.82", "Year outstanding": "£0", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1016, 'adaam-ah', 'Adaam Ah', 'Ealing · Leila (mother)', 'Outstanding', 1320.00, '{"Services": "90'' Multi-Activity (Sun)", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "LA invoice (Care in Finance)", "Term": "Summer term 2026", "Cost": "£120 / session", "Sessions": "11 (projected · Sun)", "Invoice": "—", "VAT": "Exempt", "Next": "Yr 25/26: £2,640 billed · £2,640 paid · Summer not yet invoiced (≈£1,320)", "Summer basis": "projected 11 × £120 (Sun; summer not yet invoiced)", "Year billed (25/26)": "£2,640", "Year received (25/26)": "£2,640", "Year outstanding": "£0", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1017, 'amaar-ah', 'Amaar Ah', 'Ealing · Leila (mother)', 'Outstanding', 1320.00, '{"Services": "90'' Multi-Activity (Sun)", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "LA invoice (Care in Finance)", "Term": "Summer term 2026", "Cost": "£120 / session", "Sessions": "11 (projected · Sun)", "Invoice": "—", "VAT": "Exempt", "Next": "Yr 25/26: £2,640 billed · £2,640 paid · Summer not yet invoiced (≈£1,320)", "Summer basis": "projected 11 × £120 (Sun; summer not yet invoiced)", "Year billed (25/26)": "£2,640", "Year received (25/26)": "£2,640", "Year outstanding": "£0", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx'),
  ('LA', 1018, 'aydaan-ah', 'Aydaan Ah', 'Ealing · Leila (mother)', 'Outstanding', 1320.00, '{"Services": "90'' Multi-Activity (Sun)", "Funding": "Local authority · Ealing", "Funder": "Ealing", "Funding origin": "LA-funded", "Payer": "Local authority / NHS (pays direct)", "Payment method": "LA invoice (Care in Finance)", "Term": "Summer term 2026", "Cost": "£120 / session", "Sessions": "11 (projected · Sun)", "Invoice": "—", "VAT": "Exempt", "Next": "Yr 25/26: £2,640 billed · £2,640 paid · Summer not yet invoiced (≈£1,320)", "Summer basis": "projected 11 × £120 (Sun; summer not yet invoiced)", "Year billed (25/26)": "£2,640", "Year received (25/26)": "£2,640", "Year outstanding": "£0", "Payment status": "Outstanding"}'::json, 'LA_NHS 25_26 Payments (june 2026).xlsx');

commit;
